import { buildFinancialSnapshot } from "./model";
import type {
	FinancialDisclosurePolicy,
	FinancialWorkspace,
	PublicFinancialSnapshot,
} from "./types";

const policy: FinancialDisclosurePolicy = {
	id: "policy-v1",
	version: 1,
	treatments: {
		ordinary: "individual-redacted",
		donation: "individual-redacted",
		payroll: "period-aggregate",
		beneficiary: "confidential-total",
		legal: "confidential-total",
		security: "confidential-total",
	},
	createdAt: "2026-04-01T00:00:00.000Z",
};

const base: Omit<FinancialWorkspace, "snapshots" | "canManage" | "canPublish"> =
	{
		accounts: [
			{
				id: "finance-account-operating",
				name: "Operating checking ··1842",
				publicLabel: "Operating account",
				kind: "bank",
				source: "csv",
				currency: "USD",
				decimals: 2,
				included: true,
				lastFour: "1842",
				lastSuccessfulSyncAt: "2026-07-31T18:00:00.000Z",
				health: "healthy",
			},
			{
				id: "finance-account-card",
				name: "Operations card ··4319",
				publicLabel: "Operations card",
				kind: "card",
				source: "csv",
				currency: "USD",
				decimals: 2,
				included: true,
				lastFour: "4319",
				lastSuccessfulSyncAt: "2026-07-31T18:00:00.000Z",
				health: "healthy",
			},
			{
				id: "finance-account-cash",
				name: "Friday collection cash",
				publicLabel: "Cash collections",
				kind: "cash",
				source: "demo",
				currency: "USD",
				decimals: 2,
				included: true,
				health: "healthy",
			},
			{
				id: "finance-account-solana",
				name: "Community USDC treasury",
				publicLabel: "Community USDC treasury",
				kind: "wallet",
				source: "solana",
				currency: "USDC",
				decimals: 6,
				included: true,
				network: "devnet",
				ownerAddress: "Demo111111111111111111111111111111111111111",
				mintAddress: "DemoUSDC11111111111111111111111111111111111",
				lastSuccessfulSyncAt: "2026-07-31T18:05:00.000Z",
				health: "healthy",
				simulated: true,
			},
		],
		funds: [
			{
				id: "finance-fund-general",
				name: "General fund",
				restricted: false,
				publicDescription: "Unrestricted operating support.",
			},
			{
				id: "finance-fund-building",
				name: "Building fund",
				restricted: true,
				publicDescription: "Restricted capital and facility support.",
			},
			{
				id: "finance-fund-assistance",
				name: "Community assistance",
				restricted: true,
				publicDescription: "Restricted support for qualifying community needs.",
			},
		],
		transactions: [
			transaction(
				"donation-001",
				"finance-account-operating",
				"2026-06-04",
				"inbound",
				250000,
				"Anonymous online donation",
				"donation",
				"Contributions",
				"finance-fund-general",
			),
			transaction(
				"donation-002",
				"finance-account-operating",
				"2026-06-11",
				"inbound",
				420000,
				"Anonymous building campaign donation",
				"donation",
				"Contributions",
				"finance-fund-building",
			),
			transaction(
				"cash-001",
				"finance-account-cash",
				"2026-06-12",
				"inbound",
				186400,
				"Friday collection, dual-count sheet 2026-06-12",
				"donation",
				"Cash contributions",
				"finance-fund-general",
			),
			transaction(
				"utility-001",
				"finance-account-operating",
				"2026-06-08",
				"outbound",
				214300,
				"Electric utility statement 8841",
				"ordinary",
				"Utilities",
				"finance-fund-general",
				"Electric service",
				"Naperville Electric",
			),
			transaction(
				"supplies-001",
				"finance-account-card",
				"2026-06-17",
				"outbound",
				68950,
				"Classroom and office supplies",
				"ordinary",
				"Program supplies",
				"finance-fund-general",
				"Program and office supplies",
				"Office Supply Co.",
			),
			transaction(
				"payroll-001",
				"finance-account-operating",
				"2026-06-15",
				"outbound",
				840000,
				"June payroll — private employee roster",
				"payroll",
				"Payroll",
				"finance-fund-general",
			),
			transaction(
				"aid-001",
				"finance-account-operating",
				"2026-06-20",
				"outbound",
				125000,
				"Emergency assistance — private recipient",
				"beneficiary",
				"Direct assistance",
				"finance-fund-assistance",
			),
			transaction(
				"legal-001",
				"finance-account-operating",
				"2026-06-23",
				"outbound",
				175000,
				"Counsel invoice — privileged matter",
				"legal",
				"Professional services",
				"finance-fund-general",
			),
			{
				...transaction(
					"usdc-001",
					"finance-account-solana",
					"2026-06-27",
					"inbound",
					500_000_000,
					"Public USDC contribution",
					"donation",
					"Contributions",
					"finance-fund-building",
				),
				currency: "USDC",
				decimals: 6,
				reportingAmountMinor: 50000,
				source: "solana",
			},
			transaction(
				"current-donation",
				"finance-account-operating",
				"2026-08-03",
				"inbound",
				125000,
				"August anonymous donation",
				"donation",
				"Contributions",
				"finance-fund-general",
			),
			transaction(
				"current-utility",
				"finance-account-operating",
				"2026-08-04",
				"outbound",
				221800,
				"August electric statement",
				"ordinary",
				"Utilities",
				"finance-fund-general",
				"Electric service",
				"Naperville Electric",
			),
		],
		periods: [
			{
				id: "finance-period-2026-q2",
				label: "Q2 2026",
				startAt: "2026-04-01T00:00:00.000Z",
				endAt: "2026-06-30T23:59:59.999Z",
				status: "published",
			},
			{
				id: "finance-period-2026-q3",
				label: "Q3 2026",
				startAt: "2026-07-01T00:00:00.000Z",
				endAt: "2026-09-30T23:59:59.999Z",
				status: "draft",
			},
		],
		reconciliations: [
			...reconciliations("finance-period-2026-q2", {
				"finance-account-operating": [5000000, 4315700],
				"finance-account-card": [0, -68950],
				"finance-account-cash": [0, 186400],
				"finance-account-solana": [0, 50000],
			}),
		],
		policy,
		anchoringEnabled: false,
		anchoringNetwork: "devnet",
	};

const publishedPayload = buildFinancialSnapshot({
	organization: { slug: "icn", name: "Islamic Center of Naperville" },
	period: base.periods[0],
	accounts: base.accounts,
	funds: base.funds,
	transactions: base.transactions,
	reconciliations: base.reconciliations,
	policy,
	publishedAt: "2026-07-15T16:00:00.000Z",
	publishedBy: "Amina Razzak",
});

const snapshot: PublicFinancialSnapshot = {
	id: "financial-snapshot-q2-2026-v1",
	version: 1,
	sha256: "7ce4a696381e28d71834b4eeb86e2d0e3f8e11cde87a2a5cc473381cdca34acd",
	payload: publishedPayload,
	verification: "local",
};

export const financialSeed: FinancialWorkspace = {
	...base,
	snapshots: [snapshot],
	canManage: true,
	canPublish: true,
};

function transaction(
	id: string,
	accountId: string,
	date: string,
	direction: "inbound" | "outbound",
	amount: number,
	rawDescription: string,
	sensitivity:
		| "ordinary"
		| "donation"
		| "payroll"
		| "beneficiary"
		| "legal"
		| "security",
	category: string,
	fundId: string,
	publicDescription = "",
	publicCounterparty?: string,
) {
	return {
		id,
		accountId,
		externalId: id,
		source: "demo" as const,
		postedAt: `${date}T12:00:00.000Z`,
		direction,
		amountBaseUnits: amount,
		currency: "USD" as const,
		decimals: 2,
		reportingAmountMinor: amount,
		state: "posted" as const,
		rawDescription,
		privateCounterparty: rawDescription,
		publicDescription,
		publicCounterparty,
		category,
		fundId,
		sensitivity,
		updatedAt: `${date}T12:00:00.000Z`,
	};
}

function reconciliations(
	periodId: string,
	balances: Record<string, [number, number]>,
) {
	return Object.entries(balances).map(([accountId, [opening, closing]]) => ({
		id: `${periodId}:${accountId}`,
		periodId,
		accountId,
		openingBalanceMinor: opening,
		closingBalanceMinor: closing,
		status: "reconciled" as const,
	}));
}
