/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWorkRouteImport } from './routes/_app.work'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app.$organization.index'
import { Route as PublicOrganizationRepositoryRouteImport } from './routes/public.$organization.$repository'
import { Route as AppOrganizationRepositoryIndexRouteImport } from './routes/_app.$organization.$repository.index'
import { Route as AppOrganizationRepositoryActivityRouteImport } from './routes/_app.$organization.$repository.activity'
import { Route as AppOrganizationRepositoryRecordsRouteImport } from './routes/_app.$organization.$repository.records'
import { Route as AppOrganizationRepositorySettingsRouteImport } from './routes/_app.$organization.$repository.settings'
import { Route as AppOrganizationRepositoryChangesIndexRouteImport } from './routes/_app.$organization.$repository.changes.index'
import { Route as AppOrganizationRepositoryChangesChangeNumberRouteImport } from './routes/_app.$organization.$repository.changes.$changeNumber'
import { Route as AppOrganizationRepositoryIssuesIndexRouteImport } from './routes/_app.$organization.$repository.issues.index'
import { Route as AppOrganizationRepositoryIssuesIssueNumberRouteImport } from './routes/_app.$organization.$repository.issues.$issueNumber'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/$organization/',
  path: '/$organization/',
  getParentRoute: () => AppRoute,
} as any)
const PublicOrganizationRepositoryRoute =
  PublicOrganizationRepositoryRouteImport.update({
    id: '/public/$organization/$repository',
    path: '/public/$organization/$repository',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationRepositoryIndexRoute =
  AppOrganizationRepositoryIndexRouteImport.update({
    id: '/$organization/$repository/',
    path: '/$organization/$repository/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryActivityRoute =
  AppOrganizationRepositoryActivityRouteImport.update({
    id: '/$organization/$repository/activity',
    path: '/$organization/$repository/activity',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryRecordsRoute =
  AppOrganizationRepositoryRecordsRouteImport.update({
    id: '/$organization/$repository/records',
    path: '/$organization/$repository/records',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositorySettingsRoute =
  AppOrganizationRepositorySettingsRouteImport.update({
    id: '/$organization/$repository/settings',
    path: '/$organization/$repository/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryChangesIndexRoute =
  AppOrganizationRepositoryChangesIndexRouteImport.update({
    id: '/$organization/$repository/changes/',
    path: '/$organization/$repository/changes/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryChangesChangeNumberRoute =
  AppOrganizationRepositoryChangesChangeNumberRouteImport.update({
    id: '/$organization/$repository/changes/$changeNumber',
    path: '/$organization/$repository/changes/$changeNumber',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryIssuesIndexRoute =
  AppOrganizationRepositoryIssuesIndexRouteImport.update({
    id: '/$organization/$repository/issues/',
    path: '/$organization/$repository/issues/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryIssuesIssueNumberRoute =
  AppOrganizationRepositoryIssuesIssueNumberRouteImport.update({
    id: '/$organization/$repository/issues/$issueNumber',
    path: '/$organization/$repository/issues/$issueNumber',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/inbox': typeof AppInboxRoute
  '/settings': typeof AppSettingsRoute
  '/work': typeof AppWorkRoute
  '/public/$organization/$repository': typeof PublicOrganizationRepositoryRoute
  '/$organization/': typeof AppOrganizationIndexRoute
  '/$organization/$repository/activity': typeof AppOrganizationRepositoryActivityRoute
  '/$organization/$repository/records': typeof AppOrganizationRepositoryRecordsRoute
  '/$organization/$repository/settings': typeof AppOrganizationRepositorySettingsRoute
  '/$organization/$repository/': typeof AppOrganizationRepositoryIndexRoute
  '/$organization/$repository/changes/$changeNumber': typeof AppOrganizationRepositoryChangesChangeNumberRoute
  '/$organization/$repository/issues/$issueNumber': typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  '/$organization/$repository/changes/': typeof AppOrganizationRepositoryChangesIndexRoute
  '/$organization/$repository/issues/': typeof AppOrganizationRepositoryIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof AppInboxRoute
  '/settings': typeof AppSettingsRoute
  '/work': typeof AppWorkRoute
  '/': typeof AppIndexRoute
  '/public/$organization/$repository': typeof PublicOrganizationRepositoryRoute
  '/$organization': typeof AppOrganizationIndexRoute
  '/$organization/$repository/activity': typeof AppOrganizationRepositoryActivityRoute
  '/$organization/$repository/records': typeof AppOrganizationRepositoryRecordsRoute
  '/$organization/$repository/settings': typeof AppOrganizationRepositorySettingsRoute
  '/$organization/$repository': typeof AppOrganizationRepositoryIndexRoute
  '/$organization/$repository/changes/$changeNumber': typeof AppOrganizationRepositoryChangesChangeNumberRoute
  '/$organization/$repository/issues/$issueNumber': typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  '/$organization/$repository/changes': typeof AppOrganizationRepositoryChangesIndexRoute
  '/$organization/$repository/issues': typeof AppOrganizationRepositoryIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/work': typeof AppWorkRoute
  '/_app/': typeof AppIndexRoute
  '/public/$organization/$repository': typeof PublicOrganizationRepositoryRoute
  '/_app/$organization/': typeof AppOrganizationIndexRoute
  '/_app/$organization/$repository/activity': typeof AppOrganizationRepositoryActivityRoute
  '/_app/$organization/$repository/records': typeof AppOrganizationRepositoryRecordsRoute
  '/_app/$organization/$repository/settings': typeof AppOrganizationRepositorySettingsRoute
  '/_app/$organization/$repository/': typeof AppOrganizationRepositoryIndexRoute
  '/_app/$organization/$repository/changes/$changeNumber': typeof AppOrganizationRepositoryChangesChangeNumberRoute
  '/_app/$organization/$repository/issues/$issueNumber': typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  '/_app/$organization/$repository/changes/': typeof AppOrganizationRepositoryChangesIndexRoute
  '/_app/$organization/$repository/issues/': typeof AppOrganizationRepositoryIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/settings'
    | '/work'
    | '/public/$organization/$repository'
    | '/$organization/'
    | '/$organization/$repository/activity'
    | '/$organization/$repository/records'
    | '/$organization/$repository/settings'
    | '/$organization/$repository/'
    | '/$organization/$repository/changes/$changeNumber'
    | '/$organization/$repository/issues/$issueNumber'
    | '/$organization/$repository/changes/'
    | '/$organization/$repository/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/settings'
    | '/work'
    | '/'
    | '/public/$organization/$repository'
    | '/$organization'
    | '/$organization/$repository/activity'
    | '/$organization/$repository/records'
    | '/$organization/$repository/settings'
    | '/$organization/$repository'
    | '/$organization/$repository/changes/$changeNumber'
    | '/$organization/$repository/issues/$issueNumber'
    | '/$organization/$repository/changes'
    | '/$organization/$repository/issues'
  id:
    | '__root__'
    | '/_app'
    | '/_app/inbox'
    | '/_app/settings'
    | '/_app/work'
    | '/_app/'
    | '/public/$organization/$repository'
    | '/_app/$organization/'
    | '/_app/$organization/$repository/activity'
    | '/_app/$organization/$repository/records'
    | '/_app/$organization/$repository/settings'
    | '/_app/$organization/$repository/'
    | '/_app/$organization/$repository/changes/$changeNumber'
    | '/_app/$organization/$repository/issues/$issueNumber'
    | '/_app/$organization/$repository/changes/'
    | '/_app/$organization/$repository/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicOrganizationRepositoryRoute: typeof PublicOrganizationRepositoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/': {
      id: '/_app/$organization/'
      path: '/$organization'
      fullPath: '/$organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/$organization/$repository': {
      id: '/public/$organization/$repository'
      path: '/public/$organization/$repository'
      fullPath: '/public/$organization/$repository'
      preLoaderRoute: typeof PublicOrganizationRepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organization/$repository/': {
      id: '/_app/$organization/$repository/'
      path: '/$organization/$repository'
      fullPath: '/$organization/$repository/'
      preLoaderRoute: typeof AppOrganizationRepositoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/activity': {
      id: '/_app/$organization/$repository/activity'
      path: '/$organization/$repository/activity'
      fullPath: '/$organization/$repository/activity'
      preLoaderRoute: typeof AppOrganizationRepositoryActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/records': {
      id: '/_app/$organization/$repository/records'
      path: '/$organization/$repository/records'
      fullPath: '/$organization/$repository/records'
      preLoaderRoute: typeof AppOrganizationRepositoryRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/settings': {
      id: '/_app/$organization/$repository/settings'
      path: '/$organization/$repository/settings'
      fullPath: '/$organization/$repository/settings'
      preLoaderRoute: typeof AppOrganizationRepositorySettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/changes/': {
      id: '/_app/$organization/$repository/changes/'
      path: '/$organization/$repository/changes'
      fullPath: '/$organization/$repository/changes/'
      preLoaderRoute: typeof AppOrganizationRepositoryChangesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/changes/$changeNumber': {
      id: '/_app/$organization/$repository/changes/$changeNumber'
      path: '/$organization/$repository/changes/$changeNumber'
      fullPath: '/$organization/$repository/changes/$changeNumber'
      preLoaderRoute: typeof AppOrganizationRepositoryChangesChangeNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/issues/': {
      id: '/_app/$organization/$repository/issues/'
      path: '/$organization/$repository/issues'
      fullPath: '/$organization/$repository/issues/'
      preLoaderRoute: typeof AppOrganizationRepositoryIssuesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/issues/$issueNumber': {
      id: '/_app/$organization/$repository/issues/$issueNumber'
      path: '/$organization/$repository/issues/$issueNumber'
      fullPath: '/$organization/$repository/issues/$issueNumber'
      preLoaderRoute: typeof AppOrganizationRepositoryIssuesIssueNumberRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
  AppOrganizationRepositoryActivityRoute: typeof AppOrganizationRepositoryActivityRoute
  AppOrganizationRepositoryRecordsRoute: typeof AppOrganizationRepositoryRecordsRoute
  AppOrganizationRepositorySettingsRoute: typeof AppOrganizationRepositorySettingsRoute
  AppOrganizationRepositoryIndexRoute: typeof AppOrganizationRepositoryIndexRoute
  AppOrganizationRepositoryChangesChangeNumberRoute: typeof AppOrganizationRepositoryChangesChangeNumberRoute
  AppOrganizationRepositoryIssuesIssueNumberRoute: typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  AppOrganizationRepositoryChangesIndexRoute: typeof AppOrganizationRepositoryChangesIndexRoute
  AppOrganizationRepositoryIssuesIndexRoute: typeof AppOrganizationRepositoryIssuesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
  AppOrganizationRepositoryActivityRoute:
    AppOrganizationRepositoryActivityRoute,
  AppOrganizationRepositoryRecordsRoute: AppOrganizationRepositoryRecordsRoute,
  AppOrganizationRepositorySettingsRoute:
    AppOrganizationRepositorySettingsRoute,
  AppOrganizationRepositoryIndexRoute: AppOrganizationRepositoryIndexRoute,
  AppOrganizationRepositoryChangesChangeNumberRoute:
    AppOrganizationRepositoryChangesChangeNumberRoute,
  AppOrganizationRepositoryIssuesIssueNumberRoute:
    AppOrganizationRepositoryIssuesIssueNumberRoute,
  AppOrganizationRepositoryChangesIndexRoute:
    AppOrganizationRepositoryChangesIndexRoute,
  AppOrganizationRepositoryIssuesIndexRoute:
    AppOrganizationRepositoryIssuesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicOrganizationRepositoryRoute: PublicOrganizationRepositoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
