/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWorkRouteImport } from './routes/_app.work'
import { Route as DevApprovalReviewRouteImport } from './routes/dev.approval-review'
import { Route as VerifyCommitHashRouteImport } from './routes/verify.$commitHash'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app.$organization.index'
import { Route as AppOrganizationApprovalsRouteImport } from './routes/_app.$organization.approvals'
import { Route as AppOrganizationCommunityRouteImport } from './routes/_app.$organization.community'
import { Route as AppOrganizationFinancialsRouteImport } from './routes/_app.$organization.financials'
import { Route as AppOrganizationOverviewRouteImport } from './routes/_app.$organization.overview'
import { Route as AppOrganizationResponsibilitiesRouteImport } from './routes/_app.$organization.responsibilities'
import { Route as PublicOrganizationRepositoryRouteImport } from './routes/public.$organization.$repository'
import { Route as PublicOrganizationCommunityRouteImport } from './routes/public.$organization.community'
import { Route as PublicOrganizationFinancialsRouteImport } from './routes/public.$organization.financials'
import { Route as AppOrganizationRepositoryIndexRouteImport } from './routes/_app.$organization.$repository.index'
import { Route as AppOrganizationRepositoryActivityRouteImport } from './routes/_app.$organization.$repository.activity'
import { Route as AppOrganizationRepositoryHistoryRouteImport } from './routes/_app.$organization.$repository.history'
import { Route as AppOrganizationRepositoryRecordsRouteImport } from './routes/_app.$organization.$repository.records'
import { Route as AppOrganizationRepositorySettingsRouteImport } from './routes/_app.$organization.$repository.settings'
import { Route as AppOrganizationRepositoryChangesIndexRouteImport } from './routes/_app.$organization.$repository.changes.index'
import { Route as AppOrganizationRepositoryChangesChangeNumberRouteImport } from './routes/_app.$organization.$repository.changes.$changeNumber'
import { Route as AppOrganizationRepositoryCommitsCommitHashRouteImport } from './routes/_app.$organization.$repository.commits.$commitHash'
import { Route as AppOrganizationRepositoryIssuesIndexRouteImport } from './routes/_app.$organization.$repository.issues.index'
import { Route as AppOrganizationRepositoryIssuesIssueNumberRouteImport } from './routes/_app.$organization.$repository.issues.$issueNumber'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const DevApprovalReviewRoute = DevApprovalReviewRouteImport.update({
  id: '/dev/approval-review',
  path: '/dev/approval-review',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCommitHashRoute = VerifyCommitHashRouteImport.update({
  id: '/verify/$commitHash',
  path: '/verify/$commitHash',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/$organization/',
  path: '/$organization/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationApprovalsRoute =
  AppOrganizationApprovalsRouteImport.update({
    id: '/$organization/approvals',
    path: '/$organization/approvals',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationCommunityRoute =
  AppOrganizationCommunityRouteImport.update({
    id: '/$organization/community',
    path: '/$organization/community',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationFinancialsRoute =
  AppOrganizationFinancialsRouteImport.update({
    id: '/$organization/financials',
    path: '/$organization/financials',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationOverviewRoute = AppOrganizationOverviewRouteImport.update({
  id: '/$organization/overview',
  path: '/$organization/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationResponsibilitiesRoute =
  AppOrganizationResponsibilitiesRouteImport.update({
    id: '/$organization/responsibilities',
    path: '/$organization/responsibilities',
    getParentRoute: () => AppRoute,
  } as any)
const PublicOrganizationRepositoryRoute =
  PublicOrganizationRepositoryRouteImport.update({
    id: '/public/$organization/$repository',
    path: '/public/$organization/$repository',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicOrganizationCommunityRoute =
  PublicOrganizationCommunityRouteImport.update({
    id: '/public/$organization/community',
    path: '/public/$organization/community',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicOrganizationFinancialsRoute =
  PublicOrganizationFinancialsRouteImport.update({
    id: '/public/$organization/financials',
    path: '/public/$organization/financials',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationRepositoryIndexRoute =
  AppOrganizationRepositoryIndexRouteImport.update({
    id: '/$organization/$repository/',
    path: '/$organization/$repository/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryActivityRoute =
  AppOrganizationRepositoryActivityRouteImport.update({
    id: '/$organization/$repository/activity',
    path: '/$organization/$repository/activity',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryHistoryRoute =
  AppOrganizationRepositoryHistoryRouteImport.update({
    id: '/$organization/$repository/history',
    path: '/$organization/$repository/history',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryRecordsRoute =
  AppOrganizationRepositoryRecordsRouteImport.update({
    id: '/$organization/$repository/records',
    path: '/$organization/$repository/records',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositorySettingsRoute =
  AppOrganizationRepositorySettingsRouteImport.update({
    id: '/$organization/$repository/settings',
    path: '/$organization/$repository/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryChangesIndexRoute =
  AppOrganizationRepositoryChangesIndexRouteImport.update({
    id: '/$organization/$repository/changes/',
    path: '/$organization/$repository/changes/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryChangesChangeNumberRoute =
  AppOrganizationRepositoryChangesChangeNumberRouteImport.update({
    id: '/$organization/$repository/changes/$changeNumber',
    path: '/$organization/$repository/changes/$changeNumber',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryCommitsCommitHashRoute =
  AppOrganizationRepositoryCommitsCommitHashRouteImport.update({
    id: '/$organization/$repository/commits/$commitHash',
    path: '/$organization/$repository/commits/$commitHash',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryIssuesIndexRoute =
  AppOrganizationRepositoryIssuesIndexRouteImport.update({
    id: '/$organization/$repository/issues/',
    path: '/$organization/$repository/issues/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationRepositoryIssuesIssueNumberRoute =
  AppOrganizationRepositoryIssuesIssueNumberRouteImport.update({
    id: '/$organization/$repository/issues/$issueNumber',
    path: '/$organization/$repository/issues/$issueNumber',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/inbox': typeof AppInboxRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/work': typeof AppWorkRoute
  '/dev/approval-review': typeof DevApprovalReviewRoute
  '/verify/$commitHash': typeof VerifyCommitHashRoute
  '/$organization/approvals': typeof AppOrganizationApprovalsRoute
  '/$organization/community': typeof AppOrganizationCommunityRoute
  '/$organization/financials': typeof AppOrganizationFinancialsRoute
  '/$organization/overview': typeof AppOrganizationOverviewRoute
  '/$organization/responsibilities': typeof AppOrganizationResponsibilitiesRoute
  '/public/$organization/$repository': typeof PublicOrganizationRepositoryRoute
  '/public/$organization/community': typeof PublicOrganizationCommunityRoute
  '/public/$organization/financials': typeof PublicOrganizationFinancialsRoute
  '/$organization/': typeof AppOrganizationIndexRoute
  '/$organization/$repository/activity': typeof AppOrganizationRepositoryActivityRoute
  '/$organization/$repository/history': typeof AppOrganizationRepositoryHistoryRoute
  '/$organization/$repository/records': typeof AppOrganizationRepositoryRecordsRoute
  '/$organization/$repository/settings': typeof AppOrganizationRepositorySettingsRoute
  '/$organization/$repository/': typeof AppOrganizationRepositoryIndexRoute
  '/$organization/$repository/changes/$changeNumber': typeof AppOrganizationRepositoryChangesChangeNumberRoute
  '/$organization/$repository/commits/$commitHash': typeof AppOrganizationRepositoryCommitsCommitHashRoute
  '/$organization/$repository/issues/$issueNumber': typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  '/$organization/$repository/changes/': typeof AppOrganizationRepositoryChangesIndexRoute
  '/$organization/$repository/issues/': typeof AppOrganizationRepositoryIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof AppInboxRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/work': typeof AppWorkRoute
  '/dev/approval-review': typeof DevApprovalReviewRoute
  '/verify/$commitHash': typeof VerifyCommitHashRoute
  '/': typeof AppIndexRoute
  '/$organization/approvals': typeof AppOrganizationApprovalsRoute
  '/$organization/community': typeof AppOrganizationCommunityRoute
  '/$organization/financials': typeof AppOrganizationFinancialsRoute
  '/$organization/overview': typeof AppOrganizationOverviewRoute
  '/$organization/responsibilities': typeof AppOrganizationResponsibilitiesRoute
  '/public/$organization/$repository': typeof PublicOrganizationRepositoryRoute
  '/public/$organization/community': typeof PublicOrganizationCommunityRoute
  '/public/$organization/financials': typeof PublicOrganizationFinancialsRoute
  '/$organization': typeof AppOrganizationIndexRoute
  '/$organization/$repository/activity': typeof AppOrganizationRepositoryActivityRoute
  '/$organization/$repository/history': typeof AppOrganizationRepositoryHistoryRoute
  '/$organization/$repository/records': typeof AppOrganizationRepositoryRecordsRoute
  '/$organization/$repository/settings': typeof AppOrganizationRepositorySettingsRoute
  '/$organization/$repository': typeof AppOrganizationRepositoryIndexRoute
  '/$organization/$repository/changes/$changeNumber': typeof AppOrganizationRepositoryChangesChangeNumberRoute
  '/$organization/$repository/commits/$commitHash': typeof AppOrganizationRepositoryCommitsCommitHashRoute
  '/$organization/$repository/issues/$issueNumber': typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  '/$organization/$repository/changes': typeof AppOrganizationRepositoryChangesIndexRoute
  '/$organization/$repository/issues': typeof AppOrganizationRepositoryIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/work': typeof AppWorkRoute
  '/dev/approval-review': typeof DevApprovalReviewRoute
  '/verify/$commitHash': typeof VerifyCommitHashRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$organization/approvals': typeof AppOrganizationApprovalsRoute
  '/_app/$organization/community': typeof AppOrganizationCommunityRoute
  '/_app/$organization/financials': typeof AppOrganizationFinancialsRoute
  '/_app/$organization/overview': typeof AppOrganizationOverviewRoute
  '/_app/$organization/responsibilities': typeof AppOrganizationResponsibilitiesRoute
  '/public/$organization/$repository': typeof PublicOrganizationRepositoryRoute
  '/public/$organization/community': typeof PublicOrganizationCommunityRoute
  '/public/$organization/financials': typeof PublicOrganizationFinancialsRoute
  '/_app/$organization/': typeof AppOrganizationIndexRoute
  '/_app/$organization/$repository/activity': typeof AppOrganizationRepositoryActivityRoute
  '/_app/$organization/$repository/history': typeof AppOrganizationRepositoryHistoryRoute
  '/_app/$organization/$repository/records': typeof AppOrganizationRepositoryRecordsRoute
  '/_app/$organization/$repository/settings': typeof AppOrganizationRepositorySettingsRoute
  '/_app/$organization/$repository/': typeof AppOrganizationRepositoryIndexRoute
  '/_app/$organization/$repository/changes/$changeNumber': typeof AppOrganizationRepositoryChangesChangeNumberRoute
  '/_app/$organization/$repository/commits/$commitHash': typeof AppOrganizationRepositoryCommitsCommitHashRoute
  '/_app/$organization/$repository/issues/$issueNumber': typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  '/_app/$organization/$repository/changes/': typeof AppOrganizationRepositoryChangesIndexRoute
  '/_app/$organization/$repository/issues/': typeof AppOrganizationRepositoryIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/search'
    | '/settings'
    | '/work'
    | '/dev/approval-review'
    | '/verify/$commitHash'
    | '/$organization/approvals'
    | '/$organization/community'
    | '/$organization/financials'
    | '/$organization/overview'
    | '/$organization/responsibilities'
    | '/public/$organization/$repository'
    | '/public/$organization/community'
    | '/public/$organization/financials'
    | '/$organization/'
    | '/$organization/$repository/activity'
    | '/$organization/$repository/history'
    | '/$organization/$repository/records'
    | '/$organization/$repository/settings'
    | '/$organization/$repository/'
    | '/$organization/$repository/changes/$changeNumber'
    | '/$organization/$repository/commits/$commitHash'
    | '/$organization/$repository/issues/$issueNumber'
    | '/$organization/$repository/changes/'
    | '/$organization/$repository/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/search'
    | '/settings'
    | '/work'
    | '/dev/approval-review'
    | '/verify/$commitHash'
    | '/'
    | '/$organization/approvals'
    | '/$organization/community'
    | '/$organization/financials'
    | '/$organization/overview'
    | '/$organization/responsibilities'
    | '/public/$organization/$repository'
    | '/public/$organization/community'
    | '/public/$organization/financials'
    | '/$organization'
    | '/$organization/$repository/activity'
    | '/$organization/$repository/history'
    | '/$organization/$repository/records'
    | '/$organization/$repository/settings'
    | '/$organization/$repository'
    | '/$organization/$repository/changes/$changeNumber'
    | '/$organization/$repository/commits/$commitHash'
    | '/$organization/$repository/issues/$issueNumber'
    | '/$organization/$repository/changes'
    | '/$organization/$repository/issues'
  id:
    | '__root__'
    | '/_app'
    | '/_app/inbox'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/work'
    | '/dev/approval-review'
    | '/verify/$commitHash'
    | '/_app/'
    | '/_app/$organization/approvals'
    | '/_app/$organization/community'
    | '/_app/$organization/financials'
    | '/_app/$organization/overview'
    | '/_app/$organization/responsibilities'
    | '/public/$organization/$repository'
    | '/public/$organization/community'
    | '/public/$organization/financials'
    | '/_app/$organization/'
    | '/_app/$organization/$repository/activity'
    | '/_app/$organization/$repository/history'
    | '/_app/$organization/$repository/records'
    | '/_app/$organization/$repository/settings'
    | '/_app/$organization/$repository/'
    | '/_app/$organization/$repository/changes/$changeNumber'
    | '/_app/$organization/$repository/commits/$commitHash'
    | '/_app/$organization/$repository/issues/$issueNumber'
    | '/_app/$organization/$repository/changes/'
    | '/_app/$organization/$repository/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DevApprovalReviewRoute: typeof DevApprovalReviewRoute
  VerifyCommitHashRoute: typeof VerifyCommitHashRoute
  PublicOrganizationRepositoryRoute: typeof PublicOrganizationRepositoryRoute
  PublicOrganizationCommunityRoute: typeof PublicOrganizationCommunityRoute
  PublicOrganizationFinancialsRoute: typeof PublicOrganizationFinancialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/approval-review': {
      id: '/dev/approval-review'
      path: '/dev/approval-review'
      fullPath: '/dev/approval-review'
      preLoaderRoute: typeof DevApprovalReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$commitHash': {
      id: '/verify/$commitHash'
      path: '/verify/$commitHash'
      fullPath: '/verify/$commitHash'
      preLoaderRoute: typeof VerifyCommitHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organization/': {
      id: '/_app/$organization/'
      path: '/$organization'
      fullPath: '/$organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/approvals': {
      id: '/_app/$organization/approvals'
      path: '/$organization/approvals'
      fullPath: '/$organization/approvals'
      preLoaderRoute: typeof AppOrganizationApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/community': {
      id: '/_app/$organization/community'
      path: '/$organization/community'
      fullPath: '/$organization/community'
      preLoaderRoute: typeof AppOrganizationCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/financials': {
      id: '/_app/$organization/financials'
      path: '/$organization/financials'
      fullPath: '/$organization/financials'
      preLoaderRoute: typeof AppOrganizationFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/overview': {
      id: '/_app/$organization/overview'
      path: '/$organization/overview'
      fullPath: '/$organization/overview'
      preLoaderRoute: typeof AppOrganizationOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/responsibilities': {
      id: '/_app/$organization/responsibilities'
      path: '/$organization/responsibilities'
      fullPath: '/$organization/responsibilities'
      preLoaderRoute: typeof AppOrganizationResponsibilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/$organization/$repository': {
      id: '/public/$organization/$repository'
      path: '/public/$organization/$repository'
      fullPath: '/public/$organization/$repository'
      preLoaderRoute: typeof PublicOrganizationRepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$organization/community': {
      id: '/public/$organization/community'
      path: '/public/$organization/community'
      fullPath: '/public/$organization/community'
      preLoaderRoute: typeof PublicOrganizationCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$organization/financials': {
      id: '/public/$organization/financials'
      path: '/public/$organization/financials'
      fullPath: '/public/$organization/financials'
      preLoaderRoute: typeof PublicOrganizationFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organization/$repository/': {
      id: '/_app/$organization/$repository/'
      path: '/$organization/$repository'
      fullPath: '/$organization/$repository/'
      preLoaderRoute: typeof AppOrganizationRepositoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/activity': {
      id: '/_app/$organization/$repository/activity'
      path: '/$organization/$repository/activity'
      fullPath: '/$organization/$repository/activity'
      preLoaderRoute: typeof AppOrganizationRepositoryActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/history': {
      id: '/_app/$organization/$repository/history'
      path: '/$organization/$repository/history'
      fullPath: '/$organization/$repository/history'
      preLoaderRoute: typeof AppOrganizationRepositoryHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/records': {
      id: '/_app/$organization/$repository/records'
      path: '/$organization/$repository/records'
      fullPath: '/$organization/$repository/records'
      preLoaderRoute: typeof AppOrganizationRepositoryRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/settings': {
      id: '/_app/$organization/$repository/settings'
      path: '/$organization/$repository/settings'
      fullPath: '/$organization/$repository/settings'
      preLoaderRoute: typeof AppOrganizationRepositorySettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/changes/': {
      id: '/_app/$organization/$repository/changes/'
      path: '/$organization/$repository/changes'
      fullPath: '/$organization/$repository/changes/'
      preLoaderRoute: typeof AppOrganizationRepositoryChangesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/changes/$changeNumber': {
      id: '/_app/$organization/$repository/changes/$changeNumber'
      path: '/$organization/$repository/changes/$changeNumber'
      fullPath: '/$organization/$repository/changes/$changeNumber'
      preLoaderRoute: typeof AppOrganizationRepositoryChangesChangeNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/commits/$commitHash': {
      id: '/_app/$organization/$repository/commits/$commitHash'
      path: '/$organization/$repository/commits/$commitHash'
      fullPath: '/$organization/$repository/commits/$commitHash'
      preLoaderRoute: typeof AppOrganizationRepositoryCommitsCommitHashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/issues/': {
      id: '/_app/$organization/$repository/issues/'
      path: '/$organization/$repository/issues'
      fullPath: '/$organization/$repository/issues/'
      preLoaderRoute: typeof AppOrganizationRepositoryIssuesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organization/$repository/issues/$issueNumber': {
      id: '/_app/$organization/$repository/issues/$issueNumber'
      path: '/$organization/$repository/issues/$issueNumber'
      fullPath: '/$organization/$repository/issues/$issueNumber'
      preLoaderRoute: typeof AppOrganizationRepositoryIssuesIssueNumberRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationApprovalsRoute: typeof AppOrganizationApprovalsRoute
  AppOrganizationCommunityRoute: typeof AppOrganizationCommunityRoute
  AppOrganizationFinancialsRoute: typeof AppOrganizationFinancialsRoute
  AppOrganizationOverviewRoute: typeof AppOrganizationOverviewRoute
  AppOrganizationResponsibilitiesRoute: typeof AppOrganizationResponsibilitiesRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
  AppOrganizationRepositoryActivityRoute: typeof AppOrganizationRepositoryActivityRoute
  AppOrganizationRepositoryHistoryRoute: typeof AppOrganizationRepositoryHistoryRoute
  AppOrganizationRepositoryRecordsRoute: typeof AppOrganizationRepositoryRecordsRoute
  AppOrganizationRepositorySettingsRoute: typeof AppOrganizationRepositorySettingsRoute
  AppOrganizationRepositoryIndexRoute: typeof AppOrganizationRepositoryIndexRoute
  AppOrganizationRepositoryChangesChangeNumberRoute: typeof AppOrganizationRepositoryChangesChangeNumberRoute
  AppOrganizationRepositoryCommitsCommitHashRoute: typeof AppOrganizationRepositoryCommitsCommitHashRoute
  AppOrganizationRepositoryIssuesIssueNumberRoute: typeof AppOrganizationRepositoryIssuesIssueNumberRoute
  AppOrganizationRepositoryChangesIndexRoute: typeof AppOrganizationRepositoryChangesIndexRoute
  AppOrganizationRepositoryIssuesIndexRoute: typeof AppOrganizationRepositoryIssuesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrganizationApprovalsRoute: AppOrganizationApprovalsRoute,
  AppOrganizationCommunityRoute: AppOrganizationCommunityRoute,
  AppOrganizationFinancialsRoute: AppOrganizationFinancialsRoute,
  AppOrganizationOverviewRoute: AppOrganizationOverviewRoute,
  AppOrganizationResponsibilitiesRoute: AppOrganizationResponsibilitiesRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
  AppOrganizationRepositoryActivityRoute:
    AppOrganizationRepositoryActivityRoute,
  AppOrganizationRepositoryHistoryRoute: AppOrganizationRepositoryHistoryRoute,
  AppOrganizationRepositoryRecordsRoute: AppOrganizationRepositoryRecordsRoute,
  AppOrganizationRepositorySettingsRoute:
    AppOrganizationRepositorySettingsRoute,
  AppOrganizationRepositoryIndexRoute: AppOrganizationRepositoryIndexRoute,
  AppOrganizationRepositoryChangesChangeNumberRoute:
    AppOrganizationRepositoryChangesChangeNumberRoute,
  AppOrganizationRepositoryCommitsCommitHashRoute:
    AppOrganizationRepositoryCommitsCommitHashRoute,
  AppOrganizationRepositoryIssuesIssueNumberRoute:
    AppOrganizationRepositoryIssuesIssueNumberRoute,
  AppOrganizationRepositoryChangesIndexRoute:
    AppOrganizationRepositoryChangesIndexRoute,
  AppOrganizationRepositoryIssuesIndexRoute:
    AppOrganizationRepositoryIssuesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DevApprovalReviewRoute: DevApprovalReviewRoute,
  VerifyCommitHashRoute: VerifyCommitHashRoute,
  PublicOrganizationRepositoryRoute: PublicOrganizationRepositoryRoute,
  PublicOrganizationCommunityRoute: PublicOrganizationCommunityRoute,
  PublicOrganizationFinancialsRoute: PublicOrganizationFinancialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
