import type { PlatformData } from "./types";

const now = "2026-07-24T16:00:00.000Z";

export const platformSeed: PlatformData = {
	organization: {
		id: "org-icn",
		slug: "icn",
		name: "Islamic Center of Naperville",
		shortName: "ICN",
		description:
			"Shared governance, compliance, funding, and public accountability records.",
	},
	viewerId: "member-muhammad",
	teams: [
		{
			id: "team-board",
			name: "Board",
			description: "Directors with formal governance authority.",
		},
		{
			id: "team-finance",
			name: "Finance Committee",
			description: "Treasury, budget, and financial review.",
		},
		{
			id: "team-compliance",
			name: "Compliance",
			description: "Operational owners for filings and obligations.",
		},
		{
			id: "team-reviewers",
			name: "Independent Reviewers",
			description: "People who verify evidence independently.",
		},
		{
			id: "team-publishers",
			name: "Authorized Publishers",
			description: "People who may release approved public records.",
		},
	],
	members: [
		{
			id: "member-muhammad",
			name: "Muhammad Rahman",
			title: "President",
			email: "muhammad@icn.example",
			initials: "MR",
			role: "organization-owner",
			teamIds: [
				"team-board",
				"team-finance",
				"team-compliance",
				"team-publishers",
			],
		},
		{
			id: "member-amina",
			name: "Amina Razzak",
			title: "Treasurer",
			email: "amina@icn.example",
			initials: "AR",
			role: "organization-admin",
			teamIds: ["team-board", "team-finance"],
		},
		{
			id: "member-maya",
			name: "Maya Patel",
			title: "Independent Reviewer",
			email: "maya@icn.example",
			initials: "MP",
			role: "reviewer",
			teamIds: ["team-board", "team-reviewers"],
		},
		{
			id: "member-daniel",
			name: "Daniel Brooks",
			title: "Compliance Director",
			email: "daniel@icn.example",
			initials: "DB",
			role: "maintainer",
			teamIds: ["team-compliance"],
		},
		{
			id: "member-omar",
			name: "Omar Shah",
			title: "Compliance Coordinator",
			email: "omar@icn.example",
			initials: "OS",
			role: "contributor",
			teamIds: ["team-compliance"],
		},
		{
			id: "member-noor",
			name: "Noor Hassan",
			title: "Finance Reviewer",
			email: "noor@icn.example",
			initials: "NH",
			role: "reviewer",
			teamIds: ["team-reviewers", "team-finance"],
		},
		{
			id: "member-samira",
			name: "Samira Khan",
			title: "Secretary",
			email: "samira@icn.example",
			initials: "SK",
			role: "organization-owner",
			teamIds: ["team-board", "team-publishers"],
		},
		{
			id: "member-fatima",
			name: "Fatima Ali",
			title: "Verified Member",
			email: "fatima@icn.example",
			initials: "FA",
			role: "verified-member",
			teamIds: [],
		},
	],
	locations: [
		{
			id: "location-main",
			name: "Community Center — Main Campus",
			shortName: "Main Campus",
		},
		{ id: "location-youth", name: "Youth Center", shortName: "Youth Center" },
		{ id: "location-school", name: "ICN School", shortName: "School" },
	],
	labels: [
		{
			id: "label-close",
			name: "Close to breach",
			color: "#b45309",
			description: "A governed deadline is approaching.",
			system: true,
		},
		{
			id: "label-breached",
			name: "Breached",
			color: "#be123c",
			description: "A required deadline has passed.",
			system: true,
		},
		{
			id: "label-processing",
			name: "Processing failed",
			color: "#be123c",
			description: "Document processing must be retried.",
			system: true,
			blocksMerge: true,
		},
		{
			id: "label-sensitive",
			name: "Sensitive",
			color: "#6d28d9",
			description: "The record contains protected information.",
			system: true,
		},
		{
			id: "label-do-not-merge",
			name: "Do not merge",
			color: "#b91c1c",
			description: "An authorized maintainer has blocked acceptance.",
			system: true,
			blocksMerge: true,
		},
		{
			id: "label-tax",
			name: "Tax",
			color: "#0969da",
			description: "Tax and exemption work.",
			system: false,
		},
		{
			id: "label-board",
			name: "Board vote",
			color: "#1a7f37",
			description: "Requires a formal board vote.",
			system: false,
		},
		{
			id: "label-public",
			name: "Public record",
			color: "#8250df",
			description: "Approved information may be published.",
			system: false,
		},
	],
	repositories: [
		{
			id: "repo-governance",
			slug: "governance",
			name: "Governance",
			description:
				"Board resolutions, policies, bylaws, minutes, and decisions.",
			prefix: "GOV",
			kind: "governance",
			visibility: "members",
			color: "#8250df",
			icon: "landmark",
			rules: {
				minimumApprovals: 3,
				requiredTeamIds: ["team-board"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: true,
				requireResolvedThreads: true,
				memberIssuesEnabled: false,
				memberCommentsEnabled: true,
				publicIntegrityAnchoring: false,
				finalizerRoles: ["organization-owner", "organization-admin"],
			},
			issueCount: 3,
			changeCount: 2,
			recordCount: 8,
			updatedAt: now,
		},
		{
			id: "repo-compliance",
			slug: "compliance",
			name: "Compliance",
			description:
				"Tax notices, filings, insurance, grants, licenses, and deadlines.",
			prefix: "COMP",
			kind: "compliance",
			visibility: "internal",
			color: "#cf222e",
			icon: "shield",
			rules: {
				minimumApprovals: 2,
				requiredTeamIds: ["team-reviewers", "team-compliance"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: true,
				requireResolvedThreads: true,
				memberIssuesEnabled: false,
				memberCommentsEnabled: false,
				publicIntegrityAnchoring: false,
				finalizerRoles: [
					"organization-owner",
					"organization-admin",
					"repository-admin",
					"maintainer",
				],
			},
			issueCount: 6,
			changeCount: 3,
			recordCount: 14,
			updatedAt: now,
		},
		{
			id: "repo-funding",
			slug: "funding",
			name: "Funding",
			description: "Budgets, proposals, expenses, and financial reports.",
			prefix: "FUND",
			kind: "funding",
			visibility: "members",
			color: "#1a7f37",
			icon: "wallet",
			rules: {
				minimumApprovals: 2,
				requiredTeamIds: ["team-finance", "team-board"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: true,
				requireResolvedThreads: true,
				memberIssuesEnabled: true,
				memberCommentsEnabled: true,
				publicIntegrityAnchoring: false,
				finalizerRoles: ["organization-owner", "organization-admin"],
			},
			issueCount: 4,
			changeCount: 2,
			recordCount: 11,
			updatedAt: now,
		},
		{
			id: "repo-transparency",
			slug: "transparency",
			name: "Transparency",
			description:
				"Public disclosures, member reports, and publication history.",
			prefix: "TRANS",
			kind: "transparency",
			visibility: "public",
			color: "#0969da",
			icon: "globe",
			rules: {
				minimumApprovals: 3,
				requiredTeamIds: ["team-reviewers", "team-board", "team-publishers"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: true,
				requireResolvedThreads: true,
				memberIssuesEnabled: true,
				memberCommentsEnabled: true,
				publicIntegrityAnchoring: true,
				finalizerRoles: ["organization-owner", "organization-admin"],
			},
			issueCount: 2,
			changeCount: 1,
			recordCount: 6,
			updatedAt: now,
		},
	],
	issues: [
		{
			id: "issue-tax-notice",
			repositoryId: "repo-compliance",
			number: 42,
			title: "Review the updated 2026 property tax notice",
			description:
				"A revised notice arrived for Main Campus. Confirm the balance, exemption status, and response deadline before accepting it into the permanent record.",
			template: "obligation",
			state: "open",
			status: "in-review",
			authorId: "member-omar",
			assigneeIds: ["member-daniel", "member-amina"],
			locationIds: ["location-main"],
			labelIds: ["label-tax", "label-close"],
			dueDate: "2026-07-29",
			createdAt: "2026-07-21T14:30:00.000Z",
			updatedAt: "2026-07-24T15:40:00.000Z",
			commentCount: 3,
			comments: [
				{
					id: "comment-tax-1",
					authorId: "member-omar",
					body: "The county portal shows a higher balance than the notice we accepted in May. I uploaded the revised notice for comparison.",
					visibility: "internal",
					createdAt: "2026-07-21T14:30:00.000Z",
				},
				{
					id: "comment-tax-2",
					authorId: "member-daniel",
					body: "Counsel confirmed that the response date needs independent verification before we proceed.",
					visibility: "internal",
					createdAt: "2026-07-22T10:15:00.000Z",
				},
			],
			linkedChangeIds: ["change-tax-notice"],
			watcherIds: ["member-amina", "member-daniel", "member-maya"],
		},
		{
			id: "issue-insurance",
			repositoryId: "repo-compliance",
			number: 41,
			title: "Renew general liability insurance",
			description:
				"Obtain the renewal binder, verify coverage limits, and accept the new policy record.",
			template: "obligation",
			state: "open",
			status: "in-progress",
			authorId: "member-daniel",
			assigneeIds: ["member-daniel"],
			locationIds: ["location-main", "location-youth", "location-school"],
			labelIds: ["label-breached"],
			dueDate: "2026-07-23",
			createdAt: "2026-06-10T09:00:00.000Z",
			updatedAt: "2026-07-24T12:00:00.000Z",
			commentCount: 2,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-daniel", "member-amina"],
			recurrence: "Annual",
		},
		{
			id: "issue-registration",
			repositoryId: "repo-compliance",
			number: 40,
			title: "File state charitable registration",
			description: "Prepare and independently verify the annual state filing.",
			template: "obligation",
			state: "open",
			status: "todo",
			authorId: "member-amina",
			assigneeIds: ["member-maya"],
			locationIds: [],
			labelIds: [],
			dueDate: "2026-10-15",
			createdAt: "2026-07-01T09:00:00.000Z",
			updatedAt: "2026-07-01T09:00:00.000Z",
			commentCount: 0,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-amina", "member-maya"],
			recurrence: "Annual",
		},
		{
			id: "issue-resolution",
			repositoryId: "repo-governance",
			number: 18,
			title: "Approve property compliance remediation plan",
			description:
				"Review the remediation plan, counsel guidance, conflicts, and proposed weekly evidence review.",
			template: "proposal",
			state: "open",
			status: "in-review",
			authorId: "member-amina",
			assigneeIds: ["member-samira"],
			locationIds: ["location-main"],
			labelIds: ["label-board"],
			dueDate: "2026-07-30",
			createdAt: "2026-07-22T13:00:00.000Z",
			updatedAt: "2026-07-24T14:00:00.000Z",
			commentCount: 6,
			comments: [],
			linkedChangeIds: ["change-resolution"],
			watcherIds: ["member-amina", "member-maya", "member-samira"],
		},
		{
			id: "issue-youth-grant",
			repositoryId: "repo-funding",
			number: 12,
			title: "Approve youth enrichment grant allocation",
			description:
				"Review the requested allocation, restrictions, and member feedback.",
			template: "proposal",
			state: "open",
			status: "in-progress",
			authorId: "member-omar",
			assigneeIds: ["member-amina"],
			locationIds: ["location-youth"],
			labelIds: [],
			dueDate: "2026-08-05",
			createdAt: "2026-07-19T11:00:00.000Z",
			updatedAt: "2026-07-23T16:00:00.000Z",
			commentCount: 14,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-amina", "member-fatima"],
		},
		{
			id: "issue-q2-report",
			repositoryId: "repo-transparency",
			number: 7,
			title: "Publish the Q2 member transparency report",
			description:
				"Complete privacy review, board approval, and publication checks for the Q2 report.",
			template: "proposal",
			state: "open",
			status: "in-review",
			authorId: "member-amina",
			assigneeIds: ["member-noor", "member-samira"],
			locationIds: [],
			labelIds: ["label-public"],
			dueDate: "2026-07-31",
			createdAt: "2026-07-17T10:00:00.000Z",
			updatedAt: "2026-07-24T15:00:00.000Z",
			commentCount: 4,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-amina", "member-noor", "member-samira"],
		},
		{
			id: "issue-completed",
			repositoryId: "repo-governance",
			number: 17,
			title: "Record Q1 board minutes",
			description: "Accept the approved minutes into the permanent record.",
			template: "general",
			state: "closed",
			status: "done",
			authorId: "member-maya",
			assigneeIds: ["member-maya"],
			locationIds: [],
			labelIds: [],
			createdAt: "2026-04-02T10:00:00.000Z",
			updatedAt: "2026-04-15T10:00:00.000Z",
			commentCount: 2,
			comments: [],
			linkedChangeIds: [],
			watcherIds: [],
		},
	],
	changeRequests: [
		{
			id: "change-tax-notice",
			repositoryId: "repo-compliance",
			number: 23,
			title: "Accept revised 2026 property tax notice",
			summary:
				"Replace the May notice with the revised county notice and record the changed balance and response deadline.",
			status: "open",
			authorId: "member-omar",
			locationIds: ["location-main"],
			labelIds: ["label-tax", "label-close"],
			linkedIssueId: "issue-tax-notice",
			targetRecordId: "record-tax-notice",
			createdAt: "2026-07-21T14:45:00.000Z",
			updatedAt: "2026-07-24T15:35:00.000Z",
			revisions: [
				{
					id: "revision-tax-2",
					number: 2,
					authorId: "member-omar",
					createdAt: "2026-07-24T15:35:00.000Z",
					message: "Add the corrected notice received from the county portal.",
					files: [
						{
							id: "file-tax-2",
							name: "2026-property-tax-notice-revised.pdf",
							mimeType: "application/pdf",
							sizeLabel: "384 KB",
							sha256: "9d18c5739e3b45e61fd31b2e618f3d77…",
							processingStatus: "ready",
						},
					],
				},
			],
			reviews: [
				{
					id: "review-tax-noor",
					reviewerId: "member-noor",
					revisionId: "revision-tax-2",
					decision: "approve",
					body: "The extracted amount and parcel identifier match the county portal.",
					createdAt: "2026-07-24T15:20:00.000Z",
					stale: false,
				},
			],
			checks: [
				{
					id: "check-malware",
					name: "File safety",
					description: "No malware or prohibited file types detected.",
					conclusion: "passed",
					required: true,
					updatedAt: "2026-07-24T15:36:00.000Z",
				},
				{
					id: "check-extraction",
					name: "Document extraction",
					description: "8 governed fields extracted with source provenance.",
					conclusion: "passed",
					required: true,
					updatedAt: "2026-07-24T15:37:00.000Z",
				},
				{
					id: "check-deadline",
					name: "Deadline policy",
					description: "Response deadline is five days away.",
					conclusion: "warning",
					required: true,
					updatedAt: "2026-07-24T15:37:00.000Z",
				},
			],
			comments: [
				{
					id: "change-comment-tax",
					authorId: "member-daniel",
					body: "Please confirm whether the exemption application reference was intentionally removed from page two.",
					visibility: "internal",
					createdAt: "2026-07-23T10:00:00.000Z",
				},
			],
			structuredDiff: [
				{
					id: "diff-balance",
					field: "Balance due",
					before: "$18,420.00",
					after: "$21,860.00",
					provenance: "Page 1 · Amount due",
					severity: "critical",
				},
				{
					id: "diff-penalty",
					field: "Penalty",
					before: "$0.00",
					after: "$1,340.00",
					provenance: "Page 1 · Penalties and interest",
					severity: "critical",
				},
				{
					id: "diff-deadline",
					field: "Response deadline",
					before: "August 15, 2026",
					after: "July 29, 2026",
					provenance: "Page 2 · Response rights",
					severity: "critical",
				},
				{
					id: "diff-status",
					field: "Exemption status",
					before: "Application pending",
					after: "Not reflected",
					provenance: "Page 1 · Property status",
					severity: "warning",
				},
			],
			textDiff: [
				{
					id: "text-1",
					type: "unchanged",
					content: "Property account 14-22-301-008 · Main Campus",
				},
				{
					id: "text-2",
					type: "removed",
					content: "Payment due August 15, 2026.",
				},
				{
					id: "text-3",
					type: "added",
					content:
						"Payment or written response must be received by July 29, 2026.",
				},
				{
					id: "text-4",
					type: "added",
					content: "Penalties and interest assessed: $1,340.00.",
				},
			],
			unresolvedThreads: 0,
			baseVersionId: "record-tax-v1",
			outOfDate: false,
			publicAfterMerge: false,
		},
		{
			id: "change-resolution",
			repositoryId: "repo-governance",
			number: 9,
			title: "Adopt the property compliance remediation plan",
			summary:
				"Authorize counsel support, weekly evidence review, and the proposed remediation budget.",
			status: "open",
			authorId: "member-amina",
			locationIds: ["location-main"],
			labelIds: ["label-board"],
			linkedIssueId: "issue-resolution",
			createdAt: "2026-07-22T13:20:00.000Z",
			updatedAt: "2026-07-24T14:30:00.000Z",
			revisions: [
				{
					id: "revision-resolution-1",
					number: 1,
					authorId: "member-amina",
					createdAt: "2026-07-22T13:20:00.000Z",
					message: "Initial board packet.",
					files: [
						{
							id: "file-resolution",
							name: "property-remediation-plan.pdf",
							mimeType: "application/pdf",
							sizeLabel: "1.2 MB",
							sha256: "e28b4fc59a770bd3438ef8f1a32fcb7a…",
							processingStatus: "ready",
						},
					],
				},
			],
			reviews: [
				{
					id: "review-resolution-maya",
					reviewerId: "member-maya",
					revisionId: "revision-resolution-1",
					decision: "approve",
					body: "The plan reflects the board packet and counsel scope.",
					createdAt: "2026-07-24T13:00:00.000Z",
					stale: false,
				},
				{
					id: "review-resolution-samira",
					reviewerId: "member-samira",
					revisionId: "revision-resolution-1",
					decision: "approve",
					body: "Approved for formal vote.",
					createdAt: "2026-07-24T13:30:00.000Z",
					stale: false,
				},
			],
			checks: [
				{
					id: "check-governance-files",
					name: "Board packet",
					description: "Required materials are attached.",
					conclusion: "passed",
					required: true,
					updatedAt: now,
				},
				{
					id: "check-formal-vote",
					name: "Formal vote",
					description: "6 of 9 eligible directors have voted; quorum is met.",
					conclusion: "passed",
					required: true,
					updatedAt: now,
				},
			],
			comments: [],
			structuredDiff: [],
			textDiff: [],
			unresolvedThreads: 0,
			outOfDate: false,
			publicAfterMerge: false,
		},
	],
	records: [
		{
			id: "record-tax-notice",
			repositoryId: "repo-compliance",
			title: "Main Campus property tax notice",
			collection: "Tax notices",
			locationIds: ["location-main"],
			visibility: "internal",
			currentVersionId: "record-tax-v1",
			versions: [
				{
					id: "record-tax-v1",
					version: 1,
					changeRequestId: "change-tax-original",
					createdAt: "2026-05-10T12:00:00.000Z",
					createdBy: "member-daniel",
					summary: "Initial 2026 county property tax notice.",
					files: [
						{
							id: "file-tax-1",
							name: "2026-property-tax-notice.pdf",
							mimeType: "application/pdf",
							sizeLabel: "342 KB",
							sha256: "08ad2430e6258f8f87515c7530bb0f29…",
							processingStatus: "ready",
						},
					],
					sha256: "08ad2430e6258f8f87515c7530bb0f29…",
				},
			],
			updatedAt: "2026-05-10T12:00:00.000Z",
		},
		{
			id: "record-bylaws",
			repositoryId: "repo-governance",
			title: "ICN bylaws",
			collection: "Governing documents",
			locationIds: [],
			visibility: "members",
			currentVersionId: "record-bylaws-v4",
			versions: [
				{
					id: "record-bylaws-v4",
					version: 4,
					changeRequestId: "change-bylaws-4",
					createdAt: "2026-03-18T12:00:00.000Z",
					createdBy: "member-maya",
					summary: "Approved board composition amendment.",
					files: [
						{
							id: "file-bylaws",
							name: "icn-bylaws-2026.pdf",
							mimeType: "application/pdf",
							sizeLabel: "624 KB",
							sha256: "2aa67f98d823c88e091cdfccf2afe63d…",
							processingStatus: "ready",
						},
					],
					sha256: "2aa67f98d823c88e091cdfccf2afe63d…",
				},
			],
			updatedAt: "2026-03-18T12:00:00.000Z",
		},
		{
			id: "record-q1-report",
			repositoryId: "repo-transparency",
			title: "Q1 2026 transparency report",
			collection: "Member reports",
			locationIds: [],
			visibility: "public",
			currentVersionId: "record-q1-v1",
			versions: [
				{
					id: "record-q1-v1",
					version: 1,
					changeRequestId: "change-q1-report",
					createdAt: "2026-04-30T12:00:00.000Z",
					createdBy: "member-samira",
					summary: "Board-approved Q1 member report.",
					files: [
						{
							id: "file-q1",
							name: "icn-q1-2026-transparency-report.pdf",
							mimeType: "application/pdf",
							sizeLabel: "1.8 MB",
							sha256: "8128cf54be4f9e05d20d00b03851a1e8…",
							processingStatus: "ready",
						},
					],
					sha256: "8128cf54be4f9e05d20d00b03851a1e8…",
					integrity: {
						status: "anchored",
						commitment:
							"5fd1fa676c159b424778b459c2933f42a62d19e84a9710275955145769013429",
						network: "devnet",
						signature:
							"4iDemoTieCamelSolanaIntegritySignatureQ12026Transparency",
						explorerUrl: "https://explorer.solana.com/?cluster=devnet",
					},
				},
			],
			updatedAt: "2026-04-30T12:00:00.000Z",
		},
	],
	providerConnections: [
		{
			id: "connection-google-demo",
			organizationId: "org-icn",
			provider: "google-drive",
			displayName: "ICN Google Workspace",
			status: "healthy",
			externalDomain: "icn.example",
			serviceIdentity: "tiecamel-records@demo-project.iam.gserviceaccount.com",
			keyVaultReference: "kv://demo/google-drive/service-account",
			capabilities: [
				"shared-drive",
				"stable-file-updates",
				"baseline-import",
				"change-notifications",
			],
			lastVerifiedAt: now,
			healthMessage:
				"Provider simulator is ready. No external data leaves TieCamel.",
			simulated: true,
		},
	],
	repositoryStorageConfigs: [
		"repo-governance",
		"repo-compliance",
		"repo-funding",
		"repo-transparency",
	].map((repositoryId) => ({
		id: `storage-${repositoryId}`,
		repositoryId,
		provider: "azure" as const,
		displayPath: "TieCamel managed records",
		version: 1,
		health: "healthy" as const,
		updatedAt: now,
	})),
	publicationJobs: [],
	baselineImports: [],
	activity: [
		{
			id: "activity-1",
			repositoryId: "repo-compliance",
			actorId: "member-noor",
			action: "approved",
			target: "Change request #23",
			detail: "Verified the extracted amount and parcel identifier.",
			createdAt: "2026-07-24T15:20:00.000Z",
			visibility: "internal",
		},
		{
			id: "activity-2",
			repositoryId: "repo-transparency",
			actorId: "member-amina",
			action: "requested review",
			target: "Q2 member transparency report",
			detail: "Requested privacy and board review.",
			createdAt: "2026-07-24T15:00:00.000Z",
			visibility: "public",
		},
		{
			id: "activity-3",
			repositoryId: "repo-governance",
			actorId: "member-samira",
			action: "approved",
			target: "Change request #9",
			detail: "Approved the remediation plan for formal vote.",
			createdAt: "2026-07-24T13:30:00.000Z",
			visibility: "internal",
		},
	],
	notifications: [
		{
			id: "notification-review",
			type: "review",
			title: "Review requested",
			body: "Accept revised 2026 property tax notice needs one more approval.",
			repositoryId: "repo-compliance",
			targetType: "change",
			targetId: "change-tax-notice",
			read: false,
			createdAt: "2026-07-24T15:40:00.000Z",
		},
		{
			id: "notification-deadline",
			type: "deadline",
			title: "Deadline approaching",
			body: "COMP-42 is due in five days.",
			repositoryId: "repo-compliance",
			targetType: "issue",
			targetId: "issue-tax-notice",
			read: false,
			createdAt: "2026-07-24T09:00:00.000Z",
		},
		{
			id: "notification-assignment",
			type: "assignment",
			title: "Assigned to you",
			body: "Publish the Q2 member transparency report.",
			repositoryId: "repo-transparency",
			targetType: "issue",
			targetId: "issue-q2-report",
			read: true,
			createdAt: "2026-07-23T12:00:00.000Z",
		},
	],
};
