import type { PlatformData } from "./types";

const now = "2026-07-24T16:00:00.000Z";

export const platformSeed: PlatformData = {
	organization: {
		id: "org-icn",
		slug: "icn",
		name: "Islamic Center of Naperville",
		shortName: "ICN",
		description:
			"Shared governance, compliance, funding, and public accountability records.",
	},
	viewerId: "member-muhammad",
	teams: [
		{
			id: "team-board",
			name: "Board",
			description: "Directors with formal governance authority.",
		},
		{
			id: "team-finance",
			name: "Finance Committee",
			description: "Treasury, budget, and financial review.",
		},
		{
			id: "team-compliance",
			name: "Compliance",
			description: "Operational owners for filings and obligations.",
		},
		{
			id: "team-reviewers",
			name: "Independent Reviewers",
			description: "People who verify evidence independently.",
		},
		{
			id: "team-publishers",
			name: "Authorized Publishers",
			description: "People who may release approved public records.",
		},
	],
	members: [
		{
			id: "member-muhammad",
			name: "Muhammad Rahman",
			title: "President",
			email: "muhammad@icn.example",
			initials: "MR",
			role: "organization-owner",
			teamIds: [
				"team-board",
				"team-finance",
				"team-compliance",
				"team-publishers",
			],
		},
		{
			id: "member-amina",
			name: "Amina Razzak",
			title: "Treasurer",
			email: "amina@icn.example",
			initials: "AR",
			role: "organization-admin",
			teamIds: ["team-board", "team-finance"],
		},
		{
			id: "member-maya",
			name: "Maya Patel",
			title: "Independent Reviewer",
			email: "maya@icn.example",
			initials: "MP",
			role: "reviewer",
			teamIds: ["team-board", "team-reviewers"],
		},
		{
			id: "member-daniel",
			name: "Daniel Brooks",
			title: "Compliance Director",
			email: "daniel@icn.example",
			initials: "DB",
			role: "maintainer",
			teamIds: ["team-compliance"],
		},
		{
			id: "member-omar",
			name: "Omar Shah",
			title: "Compliance Coordinator",
			email: "omar@icn.example",
			initials: "OS",
			role: "contributor",
			teamIds: ["team-compliance"],
		},
		{
			id: "member-noor",
			name: "Noor Hassan",
			title: "Finance Reviewer",
			email: "noor@icn.example",
			initials: "NH",
			role: "reviewer",
			teamIds: ["team-reviewers", "team-finance"],
		},
		{
			id: "member-samira",
			name: "Samira Khan",
			title: "Secretary",
			email: "samira@icn.example",
			initials: "SK",
			role: "organization-owner",
			teamIds: ["team-board", "team-publishers"],
		},
		{
			id: "member-fatima",
			name: "Fatima Ali",
			title: "Verified Member",
			email: "fatima@icn.example",
			initials: "FA",
			role: "verified-member",
			teamIds: [],
		},
	],
	locations: [
		{
			id: "location-main",
			name: "Community Center — Main Campus",
			shortName: "Main Campus",
		},
		{ id: "location-youth", name: "Youth Center", shortName: "Youth Center" },
		{ id: "location-school", name: "ICN School", shortName: "School" },
	],
	labels: [
		{
			id: "label-close",
			name: "Close to breach",
			color: "#b45309",
			description: "A governed deadline is approaching.",
			system: true,
		},
		{
			id: "label-breached",
			name: "Breached",
			color: "#be123c",
			description: "A required deadline has passed.",
			system: true,
		},
		{
			id: "label-processing",
			name: "Processing failed",
			color: "#be123c",
			description: "Document processing must be retried.",
			system: true,
			blocksMerge: true,
		},
		{
			id: "label-sensitive",
			name: "Sensitive",
			color: "#6d28d9",
			description: "The record contains protected information.",
			system: true,
		},
		{
			id: "label-do-not-merge",
			name: "Do not merge",
			color: "#b91c1c",
			description: "An authorized maintainer has blocked acceptance.",
			system: true,
			blocksMerge: true,
		},
		{
			id: "label-tax",
			name: "Tax",
			color: "#0969da",
			description: "Tax and exemption work.",
			system: false,
		},
		{
			id: "label-board",
			name: "Board vote",
			color: "#1a7f37",
			description: "Requires a formal board vote.",
			system: false,
		},
		{
			id: "label-public",
			name: "Public record",
			color: "#8250df",
			description: "Approved information may be published.",
			system: false,
		},
	],
	repositories: [
		{
			id: "repo-governance",
			slug: "governance",
			name: "Governance",
			description:
				"Board resolutions, policies, bylaws, minutes, and decisions.",
			prefix: "GOV",
			kind: "governance",
			visibility: "members",
			color: "#8250df",
			icon: "landmark",
			rules: {
				minimumApprovals: 3,
				requiredTeamIds: ["team-board"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: false,
				requireResolvedThreads: true,
				memberIssuesEnabled: false,
				memberCommentsEnabled: true,
				publicIntegrityAnchoring: false,
				finalizerRoles: ["organization-owner", "organization-admin"],
			},
			issueCount: 3,
			changeCount: 2,
			recordCount: 8,
			updatedAt: now,
		},
		{
			id: "repo-compliance",
			slug: "compliance",
			name: "Compliance",
			description:
				"Tax notices, filings, insurance, grants, licenses, and deadlines.",
			prefix: "COMP",
			kind: "compliance",
			visibility: "internal",
			color: "#cf222e",
			icon: "shield",
			rules: {
				minimumApprovals: 2,
				requiredTeamIds: ["team-reviewers", "team-compliance"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: false,
				requireResolvedThreads: true,
				memberIssuesEnabled: false,
				memberCommentsEnabled: false,
				publicIntegrityAnchoring: false,
				finalizerRoles: [
					"organization-owner",
					"organization-admin",
					"repository-admin",
					"maintainer",
				],
			},
			issueCount: 6,
			changeCount: 3,
			recordCount: 14,
			updatedAt: now,
		},
		{
			id: "repo-funding",
			slug: "funding",
			name: "Funding",
			description: "Budgets, proposals, expenses, and financial reports.",
			prefix: "FUND",
			kind: "funding",
			visibility: "members",
			color: "#1a7f37",
			icon: "wallet",
			rules: {
				minimumApprovals: 2,
				requiredTeamIds: ["team-finance", "team-board"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: false,
				requireResolvedThreads: true,
				memberIssuesEnabled: true,
				memberCommentsEnabled: true,
				publicIntegrityAnchoring: false,
				finalizerRoles: ["organization-owner", "organization-admin"],
			},
			issueCount: 4,
			changeCount: 2,
			recordCount: 11,
			updatedAt: now,
		},
		{
			id: "repo-transparency",
			slug: "transparency",
			name: "Transparency",
			description:
				"Public disclosures, member reports, and publication history.",
			prefix: "TRANS",
			kind: "transparency",
			visibility: "public",
			color: "#0969da",
			icon: "globe",
			rules: {
				minimumApprovals: 3,
				requiredTeamIds: ["team-reviewers", "team-board", "team-publishers"],
				dismissApprovalsOnRevision: true,
				prohibitSelfApproval: true,
				requireIssue: false,
				requireResolvedThreads: true,
				memberIssuesEnabled: true,
				memberCommentsEnabled: true,
				publicIntegrityAnchoring: true,
				finalizerRoles: ["organization-owner", "organization-admin"],
			},
			issueCount: 2,
			changeCount: 1,
			recordCount: 6,
			updatedAt: now,
		},
	],
	issues: [
		{
			id: "issue-tax-notice",
			repositoryId: "repo-compliance",
			number: 42,
			title: "Review the updated 2026 property tax notice",
			description:
				"A revised notice arrived for Main Campus. Confirm the balance, exemption status, and response deadline before accepting it into the permanent record.",
			template: "obligation",
			state: "open",
			status: "in-review",
			authorId: "member-omar",
			assigneeIds: ["member-daniel", "member-amina"],
			locationIds: ["location-main"],
			labelIds: ["label-tax", "label-close"],
			dueDate: "2026-07-29",
			createdAt: "2026-07-21T14:30:00.000Z",
			updatedAt: "2026-07-24T15:40:00.000Z",
			commentCount: 3,
			comments: [
				{
					id: "comment-tax-1",
					authorId: "member-omar",
					body: "The county portal shows a higher balance than the notice we accepted in May. I uploaded the revised notice for comparison.",
					visibility: "internal",
					createdAt: "2026-07-21T14:30:00.000Z",
				},
				{
					id: "comment-tax-2",
					authorId: "member-daniel",
					body: "Counsel confirmed that the response date needs independent verification before we proceed.",
					visibility: "internal",
					createdAt: "2026-07-22T10:15:00.000Z",
				},
			],
			linkedChangeIds: ["change-tax-notice"],
			watcherIds: ["member-amina", "member-daniel", "member-maya"],
			attachments: [
				{
					id: "attachment-tax-revised",
					name: "2026-property-tax-notice-revised.pdf",
					description: "Revised county notice under review",
					mimeType: "application/pdf",
					sizeLabel: "2.7 KB",
					sha256:
						"0a41adcd53d3a1e61e3641130b8719a694994db7516aac785022c8691b0461fc",
					url: "/demo-documents/2026-property-tax-notice-revised.pdf",
					storageProvider: "demo",
				},
			],
		},
		{
			id: "issue-insurance",
			repositoryId: "repo-compliance",
			number: 41,
			title: "Renew general liability insurance",
			description:
				"Obtain the renewal binder, verify coverage limits, and accept the new policy record.",
			template: "obligation",
			state: "open",
			status: "in-progress",
			authorId: "member-daniel",
			assigneeIds: ["member-daniel"],
			locationIds: ["location-main", "location-youth", "location-school"],
			labelIds: ["label-breached"],
			dueDate: "2026-07-23",
			createdAt: "2026-06-10T09:00:00.000Z",
			updatedAt: "2026-07-24T12:00:00.000Z",
			commentCount: 2,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-daniel", "member-amina"],
			attachments: [
				{
					id: "attachment-insurance-renewal",
					name: "general-liability-renewal-summary.pdf",
					description: "Renewal terms and coverage summary",
					mimeType: "application/pdf",
					sizeLabel: "2.7 KB",
					sha256:
						"2748fb402d8f7641690d10252b2c93cecf3da7efa426b79969756bfeb3d912f6",
					url: "/demo-documents/general-liability-renewal-summary.pdf",
					storageProvider: "demo",
				},
			],
			recurrence: "Annual",
		},
		{
			id: "issue-registration",
			repositoryId: "repo-compliance",
			number: 40,
			title: "File state charitable registration",
			description: "Prepare and independently verify the annual state filing.",
			template: "obligation",
			state: "open",
			status: "todo",
			authorId: "member-amina",
			assigneeIds: ["member-maya"],
			locationIds: [],
			labelIds: [],
			dueDate: "2026-10-15",
			createdAt: "2026-07-01T09:00:00.000Z",
			updatedAt: "2026-07-01T09:00:00.000Z",
			commentCount: 0,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-amina", "member-maya"],
			attachments: [
				{
					id: "attachment-registration-workpaper",
					name: "2026-charitable-registration-workpaper.pdf",
					description: "Annual filing preparation workpaper",
					mimeType: "application/pdf",
					sizeLabel: "2.7 KB",
					sha256:
						"3ec6ae944b0f6439aa12d814ca086b230b9c272956f99dad990d9f4941f4ab39",
					url: "/demo-documents/2026-charitable-registration-workpaper.pdf",
					storageProvider: "demo",
				},
			],
			recurrence: "Annual",
		},
		{
			id: "issue-resolution",
			repositoryId: "repo-governance",
			number: 18,
			title: "Approve property compliance remediation plan",
			description:
				"Review the remediation plan, counsel guidance, conflicts, and proposed weekly evidence review.",
			template: "proposal",
			state: "open",
			status: "in-review",
			authorId: "member-amina",
			assigneeIds: ["member-samira"],
			locationIds: ["location-main"],
			labelIds: ["label-board"],
			dueDate: "2026-07-30",
			createdAt: "2026-07-22T13:00:00.000Z",
			updatedAt: "2026-07-24T14:00:00.000Z",
			commentCount: 6,
			comments: [],
			linkedChangeIds: ["change-resolution"],
			watcherIds: ["member-amina", "member-maya", "member-samira"],
			attachments: [
				{
					id: "attachment-remediation-plan",
					name: "property-remediation-plan.pdf",
					description: "Proposed remediation plan and approval scope",
					mimeType: "application/pdf",
					sizeLabel: "2.8 KB",
					sha256:
						"bcdc24217ec3923c9b2be7a7564d58fe31686aa02f2923d821a7d03537575330",
					url: "/demo-documents/property-remediation-plan.pdf",
					storageProvider: "demo",
				},
			],
		},
		{
			id: "issue-youth-grant",
			repositoryId: "repo-funding",
			number: 12,
			title: "Approve youth enrichment grant allocation",
			description:
				"Review the requested allocation, restrictions, and member feedback.",
			template: "proposal",
			state: "open",
			status: "in-progress",
			authorId: "member-omar",
			assigneeIds: ["member-amina"],
			locationIds: ["location-youth"],
			labelIds: [],
			dueDate: "2026-08-05",
			createdAt: "2026-07-19T11:00:00.000Z",
			updatedAt: "2026-07-23T16:00:00.000Z",
			commentCount: 14,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-amina", "member-fatima"],
			attachments: [
				{
					id: "attachment-youth-grant",
					name: "youth-enrichment-grant-allocation-proposal.pdf",
					description: "Allocation proposal, restrictions, and member feedback",
					mimeType: "application/pdf",
					sizeLabel: "2.9 KB",
					sha256:
						"366c795f989e9d480d6a32e0399193e4478fe79f0c03b51233b1151f47184a71",
					url: "/demo-documents/youth-enrichment-grant-allocation-proposal.pdf",
					storageProvider: "demo",
				},
			],
		},
		{
			id: "issue-q2-report",
			repositoryId: "repo-transparency",
			number: 7,
			title: "Publish the Q2 member transparency report",
			description:
				"Complete privacy review, board approval, and publication checks for the Q2 report.",
			template: "proposal",
			state: "open",
			status: "in-review",
			authorId: "member-amina",
			assigneeIds: ["member-noor", "member-samira"],
			locationIds: [],
			labelIds: ["label-public"],
			dueDate: "2026-07-31",
			createdAt: "2026-07-17T10:00:00.000Z",
			updatedAt: "2026-07-24T15:00:00.000Z",
			commentCount: 4,
			comments: [],
			linkedChangeIds: [],
			watcherIds: ["member-amina", "member-noor", "member-samira"],
			attachments: [
				{
					id: "attachment-q2-transparency",
					name: "q2-2026-member-transparency-report.pdf",
					description: "Draft member report awaiting publication review",
					mimeType: "application/pdf",
					sizeLabel: "2.8 KB",
					sha256:
						"2fe01a04adce6f1a483f2d1223d8aced2764b0cbce0ea555f63c02367affb5c5",
					url: "/demo-documents/q2-2026-member-transparency-report.pdf",
					storageProvider: "demo",
				},
			],
		},
		{
			id: "issue-completed",
			repositoryId: "repo-governance",
			number: 17,
			title: "Record Q1 board minutes",
			description: "Accept the approved minutes into the permanent record.",
			template: "general",
			state: "closed",
			status: "done",
			authorId: "member-maya",
			assigneeIds: ["member-maya"],
			locationIds: [],
			labelIds: [],
			createdAt: "2026-04-02T10:00:00.000Z",
			updatedAt: "2026-04-15T10:00:00.000Z",
			commentCount: 2,
			comments: [],
			linkedChangeIds: [],
			watcherIds: [],
			attachments: [
				{
					id: "attachment-q1-board-minutes",
					name: "q1-2026-board-minutes.pdf",
					description: "Approved Q1 board meeting minutes",
					mimeType: "application/pdf",
					sizeLabel: "2.7 KB",
					sha256:
						"446e45450dd149f6ba93993d5cd0811a51c12b97f6c6c71da10aaeda40f73e74",
					url: "/demo-documents/q1-2026-board-minutes.pdf",
					storageProvider: "demo",
				},
			],
		},
	],
	changeRequests: [
		{
			id: "change-tax-notice",
			repositoryId: "repo-compliance",
			number: 23,
			title: "Accept revised 2026 property tax notice",
			summary:
				"Replace the May notice with the revised county notice and record the changed balance and response deadline.",
			status: "open",
			authorId: "member-omar",
			locationIds: ["location-main"],
			labelIds: ["label-tax", "label-close"],
			linkedIssueId: "issue-tax-notice",
			targetRecordId: "record-tax-notice",
			createdAt: "2026-07-21T14:45:00.000Z",
			updatedAt: "2026-07-24T15:35:00.000Z",
			revisions: [
				{
					id: "revision-tax-2",
					number: 2,
					authorId: "member-omar",
					createdAt: "2026-07-24T15:35:00.000Z",
					message: "Add the corrected notice received from the county portal.",
					files: [
						{
							id: "file-tax-2",
							name: "2026-property-tax-notice-revised.pdf",
							mimeType: "application/pdf",
							sizeLabel: "2.7 KB",
							sha256:
								"0a41adcd53d3a1e61e3641130b8719a694994db7516aac785022c8691b0461fc",
							previewUrl:
								"/demo-documents/2026-property-tax-notice-revised.pdf",
							processingStatus: "ready",
						},
					],
				},
			],
			reviews: [
				{
					id: "review-tax-noor",
					reviewerId: "member-noor",
					revisionId: "revision-tax-2",
					decision: "approve",
					body: "The extracted amount and parcel identifier match the county portal.",
					createdAt: "2026-07-24T15:20:00.000Z",
					stale: false,
				},
			],
			checks: [
				{
					id: "check-malware",
					name: "File safety",
					description: "No malware or prohibited file types detected.",
					conclusion: "passed",
					required: true,
					updatedAt: "2026-07-24T15:36:00.000Z",
				},
				{
					id: "check-extraction",
					name: "Document extraction",
					description:
						"Legacy demo fixture has no processor artifacts. Upload a real revision to generate a content diff.",
					conclusion: "warning",
					required: true,
					updatedAt: "2026-07-24T15:37:00.000Z",
				},
				{
					id: "check-deadline",
					name: "Deadline policy",
					description: "Response deadline is five days away.",
					conclusion: "warning",
					required: true,
					updatedAt: "2026-07-24T15:37:00.000Z",
				},
			],
			comments: [
				{
					id: "change-comment-tax",
					authorId: "member-daniel",
					body: "Please confirm whether the exemption application reference was intentionally removed from page two.",
					visibility: "internal",
					createdAt: "2026-07-23T10:00:00.000Z",
				},
			],
			structuredDiff: [],
			textDiff: [],
			artifacts: [],
			unresolvedThreads: 0,
			baseVersionId: "record-tax-v1",
			outOfDate: false,
			publicAfterMerge: false,
		},
		{
			id: "change-resolution",
			repositoryId: "repo-governance",
			number: 9,
			title: "Adopt the property compliance remediation plan",
			summary:
				"Authorize counsel support, weekly evidence review, and the proposed remediation budget.",
			status: "open",
			authorId: "member-amina",
			locationIds: ["location-main"],
			labelIds: ["label-board"],
			linkedIssueId: "issue-resolution",
			createdAt: "2026-07-22T13:20:00.000Z",
			updatedAt: "2026-07-24T14:30:00.000Z",
			revisions: [
				{
					id: "revision-resolution-1",
					number: 1,
					authorId: "member-amina",
					createdAt: "2026-07-22T13:20:00.000Z",
					message: "Initial board packet.",
					files: [
						{
							id: "file-resolution",
							name: "property-remediation-plan.pdf",
							mimeType: "application/pdf",
							sizeLabel: "2.8 KB",
							sha256:
								"bcdc24217ec3923c9b2be7a7564d58fe31686aa02f2923d821a7d03537575330",
							previewUrl: "/demo-documents/property-remediation-plan.pdf",
							processingStatus: "ready",
						},
					],
				},
			],
			reviews: [
				{
					id: "review-resolution-maya",
					reviewerId: "member-maya",
					revisionId: "revision-resolution-1",
					decision: "approve",
					body: "The plan reflects the board packet and counsel scope.",
					createdAt: "2026-07-24T13:00:00.000Z",
					stale: false,
				},
				{
					id: "review-resolution-samira",
					reviewerId: "member-samira",
					revisionId: "revision-resolution-1",
					decision: "approve",
					body: "Approved for formal vote.",
					createdAt: "2026-07-24T13:30:00.000Z",
					stale: false,
				},
			],
			checks: [
				{
					id: "check-governance-files",
					name: "Board packet",
					description: "Required materials are attached.",
					conclusion: "passed",
					required: true,
					updatedAt: now,
				},
				{
					id: "check-formal-vote",
					name: "Formal vote",
					description: "6 of 9 eligible directors have voted; quorum is met.",
					conclusion: "passed",
					required: true,
					updatedAt: now,
				},
			],
			comments: [],
			structuredDiff: [],
			textDiff: [],
			artifacts: [],
			unresolvedThreads: 0,
			outOfDate: false,
			publicAfterMerge: false,
		},
	],
	records: [
		{
			id: "record-tax-notice",
			repositoryId: "repo-compliance",
			title: "Main Campus property tax notice",
			collection: "Tax notices",
			locationIds: ["location-main"],
			visibility: "internal",
			currentVersionId: "record-tax-v1",
			versions: [
				{
					id: "record-tax-v1",
					version: 1,
					changeRequestId: "change-tax-original",
					createdAt: "2026-05-10T12:00:00.000Z",
					createdBy: "member-daniel",
					summary: "Initial 2026 county property tax notice.",
					files: [
						{
							id: "file-tax-1",
							name: "2026-property-tax-notice.pdf",
							mimeType: "application/pdf",
							sizeLabel: "2.7 KB",
							sha256:
								"c5e8b00924973685f375b55fddf54b5e91c793cf73170aae1e03bdeb0efdf39c",
							previewUrl: "/demo-documents/2026-property-tax-notice.pdf",
							processingStatus: "ready",
						},
					],
					sha256:
						"c5e8b00924973685f375b55fddf54b5e91c793cf73170aae1e03bdeb0efdf39c",
				},
			],
			updatedAt: "2026-05-10T12:00:00.000Z",
		},
		{
			id: "record-bylaws",
			repositoryId: "repo-governance",
			title: "ICN bylaws",
			collection: "Governing documents",
			locationIds: [],
			visibility: "members",
			currentVersionId: "record-bylaws-v4",
			versions: [
				{
					id: "record-bylaws-v4",
					version: 4,
					changeRequestId: "change-bylaws-4",
					createdAt: "2026-03-18T12:00:00.000Z",
					createdBy: "member-maya",
					summary: "Approved board composition amendment.",
					files: [
						{
							id: "file-bylaws",
							name: "icn-bylaws-2026.pdf",
							mimeType: "application/pdf",
							sizeLabel: "2.7 KB",
							sha256:
								"c2d107d44df81236f87a699abb1452bc7e9c9f851c2755b0f92ef618508b5f6b",
							previewUrl: "/demo-documents/icn-bylaws-2026.pdf",
							processingStatus: "ready",
						},
					],
					sha256:
						"c2d107d44df81236f87a699abb1452bc7e9c9f851c2755b0f92ef618508b5f6b",
				},
			],
			updatedAt: "2026-03-18T12:00:00.000Z",
		},
		{
			id: "record-q1-report",
			repositoryId: "repo-transparency",
			title: "Q1 2026 transparency report",
			collection: "Member reports",
			locationIds: [],
			visibility: "public",
			currentVersionId: "record-q1-v1",
			versions: [
				{
					id: "record-q1-v1",
					version: 1,
					changeRequestId: "change-q1-report",
					createdAt: "2026-04-30T12:00:00.000Z",
					createdBy: "member-samira",
					summary: "Board-approved Q1 member report.",
					files: [
						{
							id: "file-q1",
							name: "icn-q1-2026-transparency-report.pdf",
							mimeType: "application/pdf",
							sizeLabel: "2.7 KB",
							sha256:
								"6d2a94185bc5b442e9330a76742070832e8d19b886948443cb21125a1bb803fa",
							previewUrl: "/demo-documents/icn-q1-2026-transparency-report.pdf",
							processingStatus: "ready",
						},
					],
					sha256:
						"6d2a94185bc5b442e9330a76742070832e8d19b886948443cb21125a1bb803fa",
					integrity: {
						status: "anchored",
						commitment:
							"5fd1fa676c159b424778b459c2933f42a62d19e84a9710275955145769013429",
						network: "devnet",
						signature:
							"4iDemoTieCamelSolanaIntegritySignatureQ12026Transparency",
						explorerUrl: "https://explorer.solana.com/?cluster=devnet",
					},
				},
			],
			updatedAt: "2026-04-30T12:00:00.000Z",
		},
	],
	repositoryCommits: [],
	providerConnections: [
		{
			id: "connection-google-demo",
			organizationId: "org-icn",
			provider: "google-drive",
			displayName: "ICN Google Workspace",
			status: "healthy",
			externalDomain: "icn.example",
			serviceIdentity: "tiecamel-records@demo-project.iam.gserviceaccount.com",
			keyVaultReference: "kv://demo/google-drive/service-account",
			capabilities: [
				"shared-drive",
				"stable-file-updates",
				"baseline-import",
				"change-notifications",
			],
			lastVerifiedAt: now,
			healthMessage:
				"Provider simulator is ready. No external data leaves TieCamel.",
			simulated: true,
		},
	],
	repositoryStorageConfigs: [
		"repo-governance",
		"repo-compliance",
		"repo-funding",
		"repo-transparency",
	].map((repositoryId) => ({
		id: `storage-${repositoryId}`,
		repositoryId,
		provider: "azure" as const,
		displayPath: "TieCamel managed records",
		version: 1,
		health: "healthy" as const,
		updatedAt: now,
	})),
	publicationJobs: [],
	baselineImports: [],
	activity: [
		{
			id: "activity-1",
			repositoryId: "repo-compliance",
			actorId: "member-noor",
			action: "approved",
			target: "Change request #23",
			detail: "Verified the extracted amount and parcel identifier.",
			createdAt: "2026-07-24T15:20:00.000Z",
			visibility: "internal",
		},
		{
			id: "activity-2",
			repositoryId: "repo-transparency",
			actorId: "member-amina",
			action: "requested review",
			target: "Q2 member transparency report",
			detail: "Requested privacy and board review.",
			createdAt: "2026-07-24T15:00:00.000Z",
			visibility: "public",
		},
		{
			id: "activity-3",
			repositoryId: "repo-governance",
			actorId: "member-samira",
			action: "approved",
			target: "Change request #9",
			detail: "Approved the remediation plan for formal vote.",
			createdAt: "2026-07-24T13:30:00.000Z",
			visibility: "internal",
		},
	],
	notifications: [
		{
			id: "notification-review",
			type: "review",
			title: "Review requested",
			body: "Accept revised 2026 property tax notice needs one more approval.",
			repositoryId: "repo-compliance",
			targetType: "change",
			targetId: "change-tax-notice",
			read: false,
			createdAt: "2026-07-24T15:40:00.000Z",
		},
		{
			id: "notification-deadline",
			type: "deadline",
			title: "Deadline approaching",
			body: "COMP-42 is due in five days.",
			repositoryId: "repo-compliance",
			targetType: "issue",
			targetId: "issue-tax-notice",
			read: false,
			createdAt: "2026-07-24T09:00:00.000Z",
		},
		{
			id: "notification-assignment",
			type: "assignment",
			title: "Assigned to you",
			body: "Publish the Q2 member transparency report.",
			repositoryId: "repo-transparency",
			targetType: "issue",
			targetId: "issue-q2-report",
			read: true,
			createdAt: "2026-07-23T12:00:00.000Z",
		},
	],
};
